#Imagem base do container
FROM python:3.11

#Diretório de trabalho
WORKDIR /aym

#Copia toda a pasta do projeto para o diretório de trabalho
COPY . /aym/

#Instala as dependências do projeto
RUN pip install -r requirements.txt
